### ISSUE TITLE
cp command

### ISSUE THREAD

**Issue by yakuter** [yakuter/gol#5]
Copy files command.

**Comment by murat** [comment]
Hi @yakuter may I do this?

**Comment by yakuter** [comment]
Of course, thank you @murat

**Comment by murat** [comment]
Hi @yakuter, I implemented copy regular files as files or into folders and copy dir functions. Could you please review https://github.com/yakuter/gol/pull/21?

P.S: IMHO symlinks are out of scope. The current behavior is copying underlying file contents for symlinks.(I'm not sure)
